### ISSUE TITLE
use of global scope for $DISQUS_API_INTERFACES

### ISSUE THREAD

**Issue by jshanman** [disqus/disqus-php#2]
In disqusapi.php

Line 40 defines $DISQUS_API_INTERFACES:
    $DISQUS_API_INTERFACES = dsq_json_decode(file_get_contents(dirname(**FILE**) . '/interfaces.json'));

Line 53 Attempts to access it in the global scope:
    global $DISQUS_API_INTERFACES;

The problem is that Line 40 only adds that variable to the global scope if the disqusapi.php is included within the global context.  If disqusapi.php is included via class autoload, or from within any other class or function, then the $DISQUS_API_INTERFACES inside DisqusResource:__construct returns NULL

One way to fix this is to put on line 39:
    global $DISQUS_API_INTERFACES;

Another way to fix it would be to:
    - Line 53            global $DISQUS_API_INTERFACES;
    Line 54              $interface = dsq_json_decode(file_get_contents(dirname(**FILE**) . '/interfaces.json'));

**Comment by dcramer** [comment]
Definitely want to globalize this as we dont want to reload it each time. Moving the global call to the class scope will ensure its available on the local scope? Does it still need defined on the local scope?

**Comment by jshanman** [comment]
Using

```
global $DISQUS_API_INTERFACES;
```

on line 39 works for me. The global statement still needs to be on line 53 though. I include the file inside a class method and am able access $DISQUS_API_INTERFACES from the root file at the end of the script.  It also appears in $GLOBALS (which would be another way to ensure global context).
