### ISSUE TITLE
data=false code=0

### ISSUE THREAD

**Issue by shenka** [disqus/disqus-php#22]
Hi,

I'm testing disqus-php from my localhost like this:

$disqus = new DisqusAPI($secret_api);
$data = array('forum' => $forum_shortname);
return $disqus->posts->list($data);

But, 
$response = dsq_urlopen($url.$path, $post_data);
Returns, 
array(2) { ["data"]=> bool(false) ["code"]=> int(0) }

Any help would be appreciated

**Comment by shenka** [comment]
Ok, so, thanks to "curl_error($c)" I've been able to determine the error which was causing this issue.

string(146) "SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

So, if I remove the 's' from:

```
$url = 'http://'.DISQUS_API_HOST; from  (disqusapi.php: Line 97)
```

Works for me, but i wonder how can i make http request (not https) with disqus-api.

Anyone?

Thanks in advance.

**Comment by mattrobenolt** [comment]
@shenka can you give me the output of:  `curl -v https://disqus.com/ > /dev/null` from one of your servers?

**Comment by shenka** [comment]
Sure Matt, (Sorry for the long paste)

```
C:\Program Files\cURL\bin>curl -v https://disqus.com/
* Hostname was NOT found in DNS cache
*   Trying 173.192.42.190...
* Connected to disqus.com (173.192.42.190) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files\cURL\bin\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: serialNumber=t5uFqlLiY80Om8dgELEKebUSZRWgx4F/; OU=GT32184687; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=*.disqus.com
*        start date: 2014-04-08 21:09:25 GMT
*        expire date: 2016-06-10 16:41:41 GMT
*        subjectAltName: disqus.com matched
*        issuer: C=US; O=GeoTrust, Inc.; CN=RapidSSL CA
*        SSL certificate verify ok.
> GET / HTTP/1.1
> User-Agent: curl/7.36.0
> Host: disqus.com
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 24 Apr 2014 06:19:19 GMT
< Content-Type: text/html
< Content-Length: 10924
< Connection: close
< Last-Modified: Thu, 17 Apr 2014 19:42:50 GMT
< Vary: Accept-Encoding
< ETag: "53502eba-2aac"
< Expires: Thu, 24 Apr 2014 06:19:18 GMT
< Cache-Control: no-cache
< Cache-Control: private, must-revalidate
< Accept-Ranges: bytes
<
C:\Program Files\cURL\bin>
```

**Comment by mattrobenolt** [comment]
So everything there looks fine. Are you still having issues with it from PHP on the same machine?

**Comment by shenka** [comment]
No Matt,
It's not working from my localhost running apache.
Thank you.

**Comment by mattrobenolt** [comment]
Can I see your `phpinfo()` ?

**Comment by shenka** [comment]
Sure, https://drive.google.com/file/d/0B8Pe8Kwi9O2gRklGVTEzcGJFV3M/edit?usp=sharing

**Comment by mattrobenolt** [comment]
Ok, my hunch is that it has something to do with Windows.

In the meantime, if you can just change it to connect over http for you locally, that'll work. I think the solution is that we need to embed the certificate chain in the plugin and tell `curl` to use that. It seems that's what Facebook does:

https://github.com/facebook/facebook-php-sdk/blob/master/src/base_facebook.php#L982-L989
https://github.com/facebook/facebook-php-sdk/blob/master/src/fb_ca_chain_bundle.crt

**Comment by shenka** [comment]
Matt,

I don't have a server certificate installed on my localhost. Could that be the problem?

**Comment by mattrobenolt** [comment]
I don't know how php or windows works, but that sounds like a likely problem. Can you connect to any other hostnames over https? Like, Google, Twitter, or Facebook?

**Comment by shenka** [comment]
Sure, I'm able to connect. But the problem is with request from my localhost. That's why curl_error($c) was telling me that i have a problem with the SSL certificate....

string(146) "SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed"

**Comment by mattrobenolt** [comment]
I mean, with PHP. Since that's what's causing the problems here.

**Comment by tail** [comment]
Could you try this branch and see if it fixes the problem for you?  https://github.com/disqus/disqus-php/tree/ca-bundle

**Comment by shenka** [comment]
Tail, works!
Could you please explain why?
Thanks!

**Comment by tail** [comment]
Glad to hear it worked.  Judging from your `phpinfo()`, it looks like the version of curl compiled in with your PHP is old.  This includes the latest CA bundle from http://curl.haxx.se/docs/caextract.html to handle that case.

**Comment by shenka** [comment]
Awesome, Thank you Tail and Matt.
